import { GuidanceArticle } from '@/components/resources/GuidanceArticle'
import { DURING_APPOINTMENT_SECTION } from '../section'

export const metadata = {
  title: 'Why NHS England is an advocate of digital therapeutics (DTx) — NHS HealthStore',
}

export default function WhyNhsEnglandAdvocatesDtxPage() {
  return (
    <GuidanceArticle
      title="Why NHS England is an advocate of digital therapeutics (DTx)"
      section={DURING_APPOINTMENT_SECTION}
    >
      <p>
        The NHS views DTx software apps (sometimes called digital therapeutics) as an effective way to treat, manage, or
        prevent deterioration and improve health. The NHS HealthStore provides patients with safe, National Institute
        for Health and Care Excellence (NICE)-approved digital apps.
      </p>
      <p>Digital therapeutics best supports people by:</p>
      <ul className="nhsuk-list nhsuk-list--bullet">
        <li>
          enabling shorter wait times due to software-based treatments expanding access to care without needing a
          physical doctor&apos;s appointment
        </li>
        <li>making treatment and support more accessible</li>
        <li>
          reducing patient hospital visits by enabling (where appropriate) doctors to monitor long-term health
          conditions from afar, reducing patient travel and often preventing conditions from getting worse
        </li>
        <li>expanding ways of reaching high-quality care</li>
        <li>enabling doctors to ensure all patients receive the best care, in the most appropriate way</li>
      </ul>
      <p>
        Data generated by DTx apps is strictly governed to prioritise patient safety, privacy, and clinical
        effectiveness. It is primarily used to tailor direct care, monitor patient progress, and evaluate treatment
        outcomes.
      </p>
    </GuidanceArticle>
  )
}
